version: '3.2'
services:
  api:
    build: .
    command: sh -c "yarn && yarn start:dev"
    environment:
      NODE_ENV: development
      #DB
      POSTGRES_HOST: ec2-34-230-167-186.compute-1.amazonaws.com
      POSTGRES_DB: dckva9deao69ph
      POSTGRES_USER: yafklrdtmacdlf
      POSTGRES_PASSWORD: 25e8fdce3b91d2bd35bffb5e8b2afcc02f1c132c5b30c16e41d0e4f066f661e7
      POSTGRES_PORT: 5432
    depends_on:
      - db
    volumes:
      - .:/app
      - ~/.config:/root/.config
      - /node_modules
    ports:
      - '3001:3001'
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: ec2-34-230-167-186.compute-1.amazonaws.com
    ports:
      - 5432:5432
